export const COMPONENT_ACTIONS = {
	REQUEST: 'COMPONENT_REQUEST',
	SUCCESS: 'COMPONENT_SUCCESS',
	FAILURE: 'COMPONENT_FAILURE',
	LINE_INDEX_CHANGE: 'LINE_INDEX_CHANGE',
	DESELECT_LINE_AND_VIEW: 'DESELECT_LINE_AND_VIEW'
}
