export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const HIDE_POST = 'HIDE_POST'


export const VIEW_ACTIONS = {
	REQUEST: 'VIEW_REQUEST',
	SUCCESS: 'VIEW_SUCCESS',
	FAILURE: 'VIEW_FAILURE'
}

export const LINE_ACTIONS = {
	LINE_INDEX_CHANGE: 'LINE_INDEX_CHANGE',
	DESELECT_LINE_AND_VIEW: 'DESELECT_LINE_AND_VIEW'
}

export const SITE_ACTIONS = {
	REQUEST: 'SITE_REQUEST',
	SUCCESS: 'SITE_SUCCESS',
	FAILURE: 'SITE_FAILURE'
}